=== invicticide/fractive/src/ProjectSchema.json
{
	"$schema": "http://json-schema.org/schema#",
	"title": "Fractive Project",
	"description": "",
	"type": "object",
	"properties": {
		"title": { "type": "string", "description": "The game title that will be shown to players" },
		"author": { "type": "string", "description": "The author name that will be shown to players" },
		"description": { "type": "string", "description": "The long-form game description that will be shown to players" },
		"website": { "type": "string", "description": "A web URL that will be shown to players" },
		"markdown": {
			"type": "array",
			"items": { "type": "string" },
			"uniqueItems": true,
			"description": "List of glob-style patterns for locating Markdown source files. These are compiled in the order in which they appear."
		},
		"javascript": {
			"type": "array",
			"items": { "type": "string" },
			"uniqueItems": true,
			"description": "List of glob-style patterns for locating Javascript files reside. These are imported in the order in which they appear."
		},
		"assets": {
			"type": "array",
			"items": { "type": "string" },
			"uniqueItems": true,
			"description": "List of glob-style patterns for locating additional asset files. These are imported in the order in which they appear."
		},
		"ignore": {
			"type": "array",
			"items": { "type": "string" },
			"uniqueItems": true,
			"description": "List of glob-style patterns for files to ignore. Ignores are applied when searching for Markdown files, Javascript files, and asset files."
		},
		"aliases": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"alias": { "type": "string" },
					"replaceWith": { "type": "string" },
					"end": { "type": "string" }
				}
			},
			"uniqueItems": true,
			"description": ""
		},
		"template": { "type": "string", "description": "The HTML template file to use for the final story output" },
		"output": { "type": "string", "description": "The folder where the final story files will be saved" },
		"outputFormat": { "enum": [ "prettify", "minify", "default" ], "description": "Options: 'minify' to minify the final story HTML (reduces file size but makes the HTML source much less human-readable), 'prettify' to prettify the final story HTML into human-readable HTML, 'default' for no additional processing"  },
		"linkTooltips": { "type": "boolean", "description": "If true, show a tooltip on macro links indicating the macro destination. (Useful for dev, but you probably want to disable it for release.)" },
		"linkTags": {
			"type": "object",
			"description": "Raw HTML to be inserted at the end of different Fractive link types.",
			"properties": {
				"external": { "type": "string", "description": "Tag for external links." },
				"inline": { "type": "string", "description": "Tag for inline links." },
				"section": { "type": "string", "description": "Tag for links between sections." }
			}
		},
		"backButtonHTML": { "type": "string", "description": "Raw HTML inserted in the place where the back button is defined to be." }
	},
	"additionalProperties": false
}

=== invicticide/fractive/examples/tags/fractive.json
{
	"title": "basic",
	"template": "../../templates/basic.html",
	"linkTooltips": true,
	"linkTags": {
		"external": "&nbsp;<i class=\"fa fa-external-link\" aria-hidden=\"true\"></i>",
		"inline": "&nbsp;<i class=\"fa fa-exclamation\" aria-hidden=\"true\"></i>",
		"section": "&nbsp;<i class=\"fa fa-arrow-right\" aria-hidden=\"true\"></i>",
		"function": "&nbsp;<i class=\"fa fa-bolt\" aria-hidden=\"true\"></i>"
	}
}
